#!/bin/sh
source /boot/config/plugins/openvpnserver/openvpnserver_cert.cfg

if [ "$INSTALL_ON_BOOT" = "enable" ]; then	
	 # Start OpenVPN server
	logger "Starting OpenVPN Server"
	/etc/rc.d/rc.openvpnserver start | logger
fi
